### ISSUE TITLE
Take up/deprivation plot and scatter

### ISSUE THREAD

**Issue by namor562** [nhsbsa-data-analytics/nhs-low-income-scheme-scrollytell#23]
In the map can we make the tool tip a static chart at all that changes when the LA is selected?
Then can we reinstate the % in the tooltip for each region so that we don't need the key 
Can we add 'decile' to x axis title on the tool tip of the plots in the map?
Can we change the key on the scatterplot to 'Selected Local authority' and Other Local Authority'
Should we have a title at the top above the map ' Estimated take-up of NHS Low Income Scheme by Index of Multiple Deprivation for English Local Authorities (2015/16 to 2020/21)' and remove the title above the plot?
Also move the note to the bottom?

**Comment by nhsbsa-kaygo** [comment]
- [x] In the map can we make the tool tip a static chart at all that changes when the LA is selected?
**Not sure I can do with tooltip chart (it's rather limited as it is tooltip...)**
- [x] Then can we reinstate the % in the tooltip for each region so that we don't need the key
**Didn't understand this one.. need quick discussion**
- [x] Can we add 'decile' to x axis title on the tool tip of the plots in the map?
- [x] Can we change the key on the scatterplot to 'Selected Local authority' and Other Local Authority'
- [x] Should we have a title at the top above the map ' Estimated take-up of NHS Low Income Scheme by Index of Multiple Deprivation for English Local Authorities (2015/16 to 2020/21)' and remove the title above the plot?
- [x]  Also move the note to the bottom? **It is moved bottom in the map but can do bottom of the plot??**

**Comment by nhsbsa-kaygo** [comment]
- [x] LA map with IMD bar chart
- [x] Animation back on both Map and Scatterplot

**Comment by nhsbsa-kaygo** [comment]
Left it open as we need to discuss dynamic text. At the moment, it changes when we select Financial Year from the drop down menu.
