### ISSUE TITLE
Number of NHS LIS student applications in England (2015/16 to 2020/21)

### ISSUE THREAD

**Issue by namor562** [nhsbsa-data-analytics/nhs-low-income-scheme-scrollytell#24]
Possibly replace with a line chart, could we distinguish better. If we are comparing students/non students as opposed to students/overall, can I have the % change for non students (15/16 to 19/20) so that I can put this in the text rather than overall?
Is it worth some distinguishing successful/not successful - one to discuss

**Comment by nhsbsa-kaygo** [comment]
@NadineMorrisroe:
 _If we are comparing students/non students as opposed to students/overall, can I have the % change for non students (15/16 to 19/20) so that I can put this in the text rather than overall?_
**Total number of Non student applications decreased by 10.46%** (268,827 to 240,714). 
Changed scrolly text: _**This compares to 10% non student applications**_

**Comment by nhsbsa-kaygo** [comment]
added to this issue (#17). (avoid creating too many small branches)

**Comment by nhsbsa-kaygo** [comment]
@NadineMorrisroe , I have changed two but not sure about the last comment _(Is it worth some distinguishing successful/not successful - one to discuss)_. I will leave it open for the quick discussion around this.
